# Cleaning Data

## Importing data

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
sequence = pd.read_csv('../data/raw/sequences.csv')

/var/folders/sd/p80bpffj1hlgflffbd1p2r_w0000gn/T/ipykernel_80972/2788674502.py:1: DtypeWarning: Columns (3,4,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  sequence = pd.read_csv('../data/raw/sequences.csv')

## head, tail, shape, data types

In [13]:
sequence.head(10)

,Accession,Organism_Name,Species,Genotype,Isolate,Length,Nuc_Completeness,Geo_Location,Host,Tissue_Specimen_Source,Submitters,Collection_Date,Release_Date,Molecule_type
0,NC_138438,Red panda feces-associated circular DNA virus 12,Alohovirus ailgensis,NaN,Rpf011unssDNA01-5,2820,complete,China: Sichuan Province,Ailurus fulgens,feces,"Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...",2020-05,2026-04-07,ssDNA
1,NC_138461,Red panda feces-associated circular DNA virus 11,Protegovirus ailuris,NaN,AliP02cress04-2015,2497,complete,China: Sichuan Province,Ailurus fulgens,feces,"Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...",2015,2026-04-07,ssDNA
2,NC_097195,Pacific flying fox faeces associated circular ...,Pekavirus fuais,NaN,Tbat_38855,2214,complete,Tonga,Pteropus tonganus,feces,"Male,M.F., Kraberger,S., Stainton,D., Kami,V.,...",2014,2026-04-01,ssDNA
3,NC_099061,Bat circovirus POA/2012/V,Vegetinivirus molmolis,NaN,cluster V,1728,complete,Brazil,Chiroptera,feces,"Lima,F.E., Cibulski,S.P., Dos Santos,H.F., Tei...",2012-02-13,2026-04-01,ssDNA
4,NC_116632,Delphin virus 1,Baranavirus uduis,NaN,3_2016_1939,1939,complete,Saint Vincent and the Grenadines,Orcinus orca,muscle,"Smith,K., Fielding,R., Schiavone,K., Hall,K., ...",2015-08-26,2026-04-01,ssDNA
5,NC_099376,Ferullusivirus minfulis,Ferullusivirus minfulis,NaN,BtMf-CV/HeN2013,1643,complete,China,Miniopterus fuliginosus,NaN,"Wu,Z., Yang,L., Ren,X., He,G., Zhang,J., Yang,...",2013-04,2026-03-31,ssDNA
6,NC_099378,Pollentivirus pleritis,Pollentivirus pleritis,NaN,BtPa-CV-3/NX2013,1881,complete,China,Plecotus auritus,NaN,"Wu,Z., Yang,L., Ren,X., He,G., Zhang,J., Yang,...",2013-06,2026-03-31,ssDNA
7,NC_129432,Audaxivirus minifulis,Audaxivirus minifulis,NaN,BtMf-CV-1/GD2012,1728,complete,China,Miniopterus fuliginosus,NaN,"Wu,Z., Yang,L., Ren,X., He,G., Zhang,J., Yang,...",2012-12,2026-03-31,ssDNA
8,NC_138392,Audaxivirus yotargis,Audaxivirus yotargis,NaN,NaN,1638,complete,Hungary,Myotis emarginatus,feces,"Kemenesi,G., Kurucz,K., Zana,B., Foldes,F., Ur...",2013,2026-03-31,ssDNA
9,NC_138394,Circoviridae TM-6c,Ferullusivirus baguanis,NaN,TM-6c,1696,complete,USA,Chiroptera,feces,"Li,L., Victoria,J.G., Wang,C., Jones,M., Felle...",2008-08,2026-03-31,ssDNA

In [14]:
sequence.tail(5)

,Accession,Organism_Name,Species,Genotype,Isolate,Length,Nuc_Completeness,Geo_Location,Host,Tissue_Specimen_Source,Submitters,Collection_Date,Release_Date,Molecule_type
3256598,EF421971,Porcine circovirus 2,Circovirus porcine2,NaN,Huanan-6,1767,complete,China: Dongguan,Sus scrofa,NaN,"Song,C.X., Sun,L.H., Jiang,Z.Y., Hao,Y.Q.",2006-11,2007-03-05,ssDNA(+/-)
3256599,EF421972,Porcine circovirus 2,Circovirus porcine2,NaN,Huanan-7,1767,complete,China: Dongguan,Sus scrofa,NaN,"Sun,L.H., Song,C.X., Hao,Y.Q., Jiang,Z.Y.",2006-11,2007-03-05,ssDNA(+/-)
3256600,EF421973,Porcine circovirus 2,Circovirus porcine2,NaN,Huanan-8,1767,complete,China: Hainan,Sus scrofa,NaN,"Sun,L.H., Jiang,Z.Y., Song,C.X.",2006-11,2007-03-05,ssDNA(+/-)
3256601,AY772167,Mopeia Lassa virus reassortant 29,Mopeia Lassa virus reassortant 29,NaN,NaN,7271,complete,NaN,Chlorocebus aethiops,NaN,"Lukashevich,I.S., Patterson,J., Carrion,R., Mo...",2006-05-01,2004-11-15,ssRNA(+/-)
3256602,AY772168,Mopeia Lassa virus reassortant 29,Mopeia Lassa virus reassortant 29,NaN,NaN,3402,complete,NaN,Chlorocebus aethiops,NaN,"Lukashevich,I.S., Patterson,J., Carrion,R., Mo...",2006-05-01,2004-11-15,ssRNA(+/-)

In [15]:
sequence.shape

(3256603, 14)

In [16]:
sequence.info

<bound method DataFrame.info of          Accession                                      Organism_Name  \
0        NC_138438   Red panda feces-associated circular DNA virus 12
1        NC_138461   Red panda feces-associated circular DNA virus 11
2        NC_097195  Pacific flying fox faeces associated circular ...
3        NC_099061                          Bat circovirus POA/2012/V
4        NC_116632                                    Delphin virus 1
...            ...                                                ...
3256598   EF421971                               Porcine circovirus 2
3256599   EF421972                               Porcine circovirus 2
3256600   EF421973                               Porcine circovirus 2
3256601   AY772167                  Mopeia Lassa virus reassortant 29
3256602   AY772168                  Mopeia Lassa virus reassortant 29

                                   Species Genotype             Isolate  \
0                     Alohovirus ailgensis      NaN   Rpf011unssDNA01-5
1                     Protegovirus ailuris      NaN  AliP02cress04-2015
2                          Pekavirus fuais      NaN          Tbat_38855
3                   Vegetinivirus molmolis      NaN           cluster V
4                        Baranavirus uduis      NaN         3_2016_1939
...                                    ...      ...                 ...
3256598                Circovirus porcine2      NaN            Huanan-6
3256599                Circovirus porcine2      NaN            Huanan-7
3256600                Circovirus porcine2      NaN            Huanan-8
3256601  Mopeia Lassa virus reassortant 29      NaN                 NaN
3256602  Mopeia Lassa virus reassortant 29      NaN                 NaN

         Length Nuc_Completeness                      Geo_Location  \
0          2820         complete           China: Sichuan Province
1          2497         complete           China: Sichuan Province
2          2214         complete                             Tonga
3          1728         complete                            Brazil
4          1939         complete  Saint Vincent and the Grenadines
...         ...              ...                               ...
3256598    1767         complete                   China: Dongguan
3256599    1767         complete                   China: Dongguan
3256600    1767         complete                     China: Hainan
3256601    7271         complete                               NaN
3256602    3402         complete                               NaN

                         Host Tissue_Specimen_Source  \
0             Ailurus fulgens                  feces
1             Ailurus fulgens                  feces
2           Pteropus tonganus                  feces
3                  Chiroptera                  feces
4                Orcinus orca                 muscle
...                       ...                    ...
3256598            Sus scrofa                    NaN
3256599            Sus scrofa                    NaN
3256600            Sus scrofa                    NaN
3256601  Chlorocebus aethiops                    NaN
3256602  Chlorocebus aethiops                    NaN

                                                Submitters Collection_Date  \
0        Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...         2020-05
1        Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...            2015
2        Male,M.F., Kraberger,S., Stainton,D., Kami,V.,...            2014
3        Lima,F.E., Cibulski,S.P., Dos Santos,H.F., Tei...      2012-02-13
4        Smith,K., Fielding,R., Schiavone,K., Hall,K., ...      2015-08-26
...                                                    ...             ...
3256598          Song,C.X., Sun,L.H., Jiang,Z.Y., Hao,Y.Q.         2006-11
3256599          Sun,L.H., Song,C.X., Hao,Y.Q., Jiang,Z.Y.         2006-11
3256600                    Sun,L.H., Jiang,Z.Y., Song,C.X.         2006-11
3256601  Lukashevich,I.S., Patterson,J., Carrion,R., Mo...      2006-05-01
3256602  Lukashevich,I.S., Patterson,J., Carrion,R., Mo...      2006-05-01

        Release_Date Molecule_type
0         2026-04-07         ssDNA
1         2026-04-07         ssDNA
2         2026-04-01         ssDNA
3         2026-04-01         ssDNA
4         2026-04-01         ssDNA
...              ...           ...
3256598   2007-03-05    ssDNA(+/-)
3256599   2007-03-05    ssDNA(+/-)
3256600   2007-03-05    ssDNA(+/-)
3256601   2004-11-15    ssRNA(+/-)
3256602   2004-11-15    ssRNA(+/-)

[3256603 rows x 14 columns]>

## check for missing values

In [17]:
# missing values in each column
sequence.isnull().sum()

Accession                       0
Organism_Name                   0
Species                         8
Genotype                  3207708
Isolate                   1549946
Length                          0
Nuc_Completeness                0
Geo_Location                  336
Host                            0
Tissue_Specimen_Source    2075732
Submitters                1386678
Collection_Date                 0
Release_Date                    0
Molecule_type                   0
dtype: int64

## what each row title means

`Accession:` unique number associated with the data

`Organism_Name:` the organism that carries the virus

`Species:` the species of virus present in the organism

`Genotype:` the specific DNA sequence for the virus

`Isolate:` a specific strain of the virus that was collected from a specimen

`Length:` how long the virus's geome sequence is (how many nucleotides long)

`Nuc_Completeness:`whether or not nucleotide sequence is completed

`Geo_Location:` country or area where the virus strain was found

`Host:` animal where the virus strain was found

`Tissue_Speciman_Source:` where the virus tissue was found from the animal (feces, blood, saliva, tissue, etc)

`Submitters:` the people or institution who submitted the virus to the database

`Collection_Date:` the date the virus was collected from the host

`Release_Date:` the date the virus information was published/released to the database

`Molecule_type`:

## check for duplicate values

In [18]:
sequence.duplicated().sum()

np.int64(0)

In [19]:
# Count how many duplicates in Accession
sequence['Accession'].duplicated().sum()

np.int64(0)

In [20]:
# Count how many duplicates in Accession
sequence['Organism_Name'].duplicated().sum()

np.int64(3250617)

In [21]:
# access genotype examples
sequence_with_genotype = sequence[sequence['Genotype'].notna()]
sequence_with_genotype.head()

,Accession,Organism_Name,Species,Genotype,Isolate,Length,Nuc_Completeness,Geo_Location,Host,Tissue_Specimen_Source,Submitters,Collection_Date,Release_Date,Molecule_type
195,NC_075965,Mastadenovirus porcusquartum,Mastadenovirus porcusquartum,4,HNU1,31743,complete,China,Sus scrofa,NaN,"Liu,S.-J., Wang,Q., Li,T.-T., Zhang,S.-H., Li,...",2018-07,2023-05-04,dsDNA
197,NC_075980,Teschovirus A,Teschovirus asilesi,17,HuN41,6931,complete,China,Sus scrofa,NaN,"Yang,T., Yu,X.",2017-10,2023-05-04,ssRNA(+)
368,NC_063383,Monkeypox virus,Orthopoxvirus monkeypox,IIb,MPXV-M5312_HM12_Rivers,197209,complete,Nigeria: Rivers State,Homo sapiens,NaN,"Mauldin,M.R., McCollum,A.M., Nakazawa,Y.J., Ma...",2018-08,2022-05-30,dsDNA
447,NC_044856,Norovirus GI,Norovirus norwalkense,GI.Pg-GI.7,NaN,7734,complete,Bangladesh,Homo sapiens,feces,"Nelson,M.I., Mahfuz,M., Chhabra,P., Haque,R., ...",2011-07-06,2019-09-26,ssRNA(+)
687,NC_039028,Squirrel monkey simian foamy virus,Simiispumavirus saisci,SFV4,1224,11684,complete,USA,Saimiri,oronasopharynx,"Pacheco,B., Finzi,A., McGee-Estrada,K., Sodros...",2009-11,2018-08-24,ssRNA-RT

## check basic stats (idk what this means)

In [22]:
sequence.describe()

             Length
count  3.256603e+06
mean   2.946662e+04
std    7.919259e+03
min    1.140000e+02
25%    2.975300e+04
50%    2.984100e+04
75%    2.988400e+04
max    6.599500e+05