# Cleaning Data

## Importing data

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
sequence = pd.read_csv('../data/raw/sequences.csv')

/var/folders/vm/dvt0998j0_1dk6mw3c5fydf80000gn/T/ipykernel_1162/2788674502.py:1: DtypeWarning: Columns (3,4,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  sequence = pd.read_csv('../data/raw/sequences.csv')

## head, tail, shape, data types

In [7]:
sequence.head(10)

,Accession,Organism_Name,Species,Genotype,Isolate,Length,Nuc_Completeness,Geo_Location,Host,Tissue_Specimen_Source,Submitters,Collection_Date,Release_Date,Molecule_type
0,NC_138438,Red panda feces-associated circular DNA virus 12,Alohovirus ailgensis,NaN,Rpf011unssDNA01-5,2820,complete,China: Sichuan Province,Ailurus fulgens,feces,"Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...",2020-05,2026-04-07,ssDNA
1,NC_138461,Red panda feces-associated circular DNA virus 11,Protegovirus ailuris,NaN,AliP02cress04-2015,2497,complete,China: Sichuan Province,Ailurus fulgens,feces,"Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...",2015,2026-04-07,ssDNA
2,NC_097195,Pacific flying fox faeces associated circular ...,Pekavirus fuais,NaN,Tbat_38855,2214,complete,Tonga,Pteropus tonganus,feces,"Male,M.F., Kraberger,S., Stainton,D., Kami,V.,...",2014,2026-04-01,ssDNA
3,NC_099061,Bat circovirus POA/2012/V,Vegetinivirus molmolis,NaN,cluster V,1728,complete,Brazil,Chiroptera,feces,"Lima,F.E., Cibulski,S.P., Dos Santos,H.F., Tei...",2012-02-13,2026-04-01,ssDNA
4,NC_116632,Delphin virus 1,Baranavirus uduis,NaN,3_2016_1939,1939,complete,Saint Vincent and the Grenadines,Orcinus orca,muscle,"Smith,K., Fielding,R., Schiavone,K., Hall,K., ...",2015-08-26,2026-04-01,ssDNA
5,NC_099376,Ferullusivirus minfulis,Ferullusivirus minfulis,NaN,BtMf-CV/HeN2013,1643,complete,China,Miniopterus fuliginosus,NaN,"Wu,Z., Yang,L., Ren,X., He,G., Zhang,J., Yang,...",2013-04,2026-03-31,ssDNA
6,NC_099378,Pollentivirus pleritis,Pollentivirus pleritis,NaN,BtPa-CV-3/NX2013,1881,complete,China,Plecotus auritus,NaN,"Wu,Z., Yang,L., Ren,X., He,G., Zhang,J., Yang,...",2013-06,2026-03-31,ssDNA
7,NC_129432,Audaxivirus minifulis,Audaxivirus minifulis,NaN,BtMf-CV-1/GD2012,1728,complete,China,Miniopterus fuliginosus,NaN,"Wu,Z., Yang,L., Ren,X., He,G., Zhang,J., Yang,...",2012-12,2026-03-31,ssDNA
8,NC_138392,Audaxivirus yotargis,Audaxivirus yotargis,NaN,NaN,1638,complete,Hungary,Myotis emarginatus,feces,"Kemenesi,G., Kurucz,K., Zana,B., Foldes,F., Ur...",2013,2026-03-31,ssDNA
9,NC_138394,Circoviridae TM-6c,Ferullusivirus baguanis,NaN,TM-6c,1696,complete,USA,Chiroptera,feces,"Li,L., Victoria,J.G., Wang,C., Jones,M., Felle...",2008-08,2026-03-31,ssDNA

In [8]:
sequence.tail(5)

,Accession,Organism_Name,Species,Genotype,Isolate,Length,Nuc_Completeness,Geo_Location,Host,Tissue_Specimen_Source,Submitters,Collection_Date,Release_Date,Molecule_type
3256598,EF421971,Porcine circovirus 2,Circovirus porcine2,NaN,Huanan-6,1767,complete,China: Dongguan,Sus scrofa,NaN,"Song,C.X., Sun,L.H., Jiang,Z.Y., Hao,Y.Q.",2006-11,2007-03-05,ssDNA(+/-)
3256599,EF421972,Porcine circovirus 2,Circovirus porcine2,NaN,Huanan-7,1767,complete,China: Dongguan,Sus scrofa,NaN,"Sun,L.H., Song,C.X., Hao,Y.Q., Jiang,Z.Y.",2006-11,2007-03-05,ssDNA(+/-)
3256600,EF421973,Porcine circovirus 2,Circovirus porcine2,NaN,Huanan-8,1767,complete,China: Hainan,Sus scrofa,NaN,"Sun,L.H., Jiang,Z.Y., Song,C.X.",2006-11,2007-03-05,ssDNA(+/-)
3256601,AY772167,Mopeia Lassa virus reassortant 29,Mopeia Lassa virus reassortant 29,NaN,NaN,7271,complete,NaN,Chlorocebus aethiops,NaN,"Lukashevich,I.S., Patterson,J., Carrion,R., Mo...",2006-05-01,2004-11-15,ssRNA(+/-)
3256602,AY772168,Mopeia Lassa virus reassortant 29,Mopeia Lassa virus reassortant 29,NaN,NaN,3402,complete,NaN,Chlorocebus aethiops,NaN,"Lukashevich,I.S., Patterson,J., Carrion,R., Mo...",2006-05-01,2004-11-15,ssRNA(+/-)

In [9]:
sequence.shape

(3256603, 14)

In [10]:
sequence.info

<bound method DataFrame.info of          Accession                                      Organism_Name  \
0        NC_138438   Red panda feces-associated circular DNA virus 12
1        NC_138461   Red panda feces-associated circular DNA virus 11
2        NC_097195  Pacific flying fox faeces associated circular ...
3        NC_099061                          Bat circovirus POA/2012/V
4        NC_116632                                    Delphin virus 1
...            ...                                                ...
3256598   EF421971                               Porcine circovirus 2
3256599   EF421972                               Porcine circovirus 2
3256600   EF421973                               Porcine circovirus 2
3256601   AY772167                  Mopeia Lassa virus reassortant 29
3256602   AY772168                  Mopeia Lassa virus reassortant 29

                                   Species Genotype             Isolate  \
0                     Alohovirus ailgensis      NaN   Rpf011unssDNA01-5
1                     Protegovirus ailuris      NaN  AliP02cress04-2015
2                          Pekavirus fuais      NaN          Tbat_38855
3                   Vegetinivirus molmolis      NaN           cluster V
4                        Baranavirus uduis      NaN         3_2016_1939
...                                    ...      ...                 ...
3256598                Circovirus porcine2      NaN            Huanan-6
3256599                Circovirus porcine2      NaN            Huanan-7
3256600                Circovirus porcine2      NaN            Huanan-8
3256601  Mopeia Lassa virus reassortant 29      NaN                 NaN
3256602  Mopeia Lassa virus reassortant 29      NaN                 NaN

         Length Nuc_Completeness                      Geo_Location  \
0          2820         complete           China: Sichuan Province
1          2497         complete           China: Sichuan Province
2          2214         complete                             Tonga
3          1728         complete                            Brazil
4          1939         complete  Saint Vincent and the Grenadines
...         ...              ...                               ...
3256598    1767         complete                   China: Dongguan
3256599    1767         complete                   China: Dongguan
3256600    1767         complete                     China: Hainan
3256601    7271         complete                               NaN
3256602    3402         complete                               NaN

                         Host Tissue_Specimen_Source  \
0             Ailurus fulgens                  feces
1             Ailurus fulgens                  feces
2           Pteropus tonganus                  feces
3                  Chiroptera                  feces
4                Orcinus orca                 muscle
...                       ...                    ...
3256598            Sus scrofa                    NaN
3256599            Sus scrofa                    NaN
3256600            Sus scrofa                    NaN
3256601  Chlorocebus aethiops                    NaN
3256602  Chlorocebus aethiops                    NaN

                                                Submitters Collection_Date  \
0        Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...         2020-05
1        Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...            2015
2        Male,M.F., Kraberger,S., Stainton,D., Kami,V.,...            2014
3        Lima,F.E., Cibulski,S.P., Dos Santos,H.F., Tei...      2012-02-13
4        Smith,K., Fielding,R., Schiavone,K., Hall,K., ...      2015-08-26
...                                                    ...             ...
3256598          Song,C.X., Sun,L.H., Jiang,Z.Y., Hao,Y.Q.         2006-11
3256599          Sun,L.H., Song,C.X., Hao,Y.Q., Jiang,Z.Y.         2006-11
3256600                    Sun,L.H., Jiang,Z.Y., Song,C.X.         2006-11
3256601  Lukashevich,I.S., Patterson,J., Carrion,R., Mo...      2006-05-01
3256602  Lukashevich,I.S., Patterson,J., Carrion,R., Mo...      2006-05-01

        Release_Date Molecule_type
0         2026-04-07         ssDNA
1         2026-04-07         ssDNA
2         2026-04-01         ssDNA
3         2026-04-01         ssDNA
4         2026-04-01         ssDNA
...              ...           ...
3256598   2007-03-05    ssDNA(+/-)
3256599   2007-03-05    ssDNA(+/-)
3256600   2007-03-05    ssDNA(+/-)
3256601   2004-11-15    ssRNA(+/-)
3256602   2004-11-15    ssRNA(+/-)

[3256603 rows x 14 columns]>

## check for missing values

In [11]:
# missing values in each column
sequence.isnull().sum()

Accession                       0
Organism_Name                   0
Species                         8
Genotype                  3207708
Isolate                   1549946
Length                          0
Nuc_Completeness                0
Geo_Location                  336
Host                            0
Tissue_Specimen_Source    2075732
Submitters                1386678
Collection_Date                 0
Release_Date                    0
Molecule_type                   0
dtype: int64

## what each row title means

`Accession:` unique number associated with the data

`Organism_Name:` the organism that carries the virus

`Species:` the species of virus present in the organism

`Genotype:` the specific DNA sequence for the virus

`Isolate:` a specific strain of the virus that was collected from a specimen

`Length:` how long the virus's geome sequence is (how many nucleotides long)

`Nuc_Completeness:`whether or not nucleotide sequence is completed

`Geo_Location:` country or area where the virus strain was found

`Host:` animal where the virus strain was found

`Tissue_Speciman_Source:` where the virus tissue was found from the animal (feces, blood, saliva, tissue, etc)

`Submitters:` the people or institution who submitted the virus to the database

`Collection_Date:` the date the virus was collected from the host

`Release_Date:` the date the virus information was published/released to the database

`Molecule_type`:

## check for duplicate values

In [15]:
sequence.duplicated().sum()

np.int64(0)

In [17]:
# Count how many duplicates in Accession
sequence['Accession'].duplicated().sum()

np.int64(0)

In [19]:
# Count how many duplicates in Accession
sequence['Organism_Name'].duplicated().sum()

np.int64(3250617)

In [20]:
# access genotype examples
sequence_with_genotype = sequence[sequence['Genotype'].notna()]
sequence_with_genotype.head()

,Accession,Organism_Name,Species,Genotype,Isolate,Length,Nuc_Completeness,Geo_Location,Host,Tissue_Specimen_Source,Submitters,Collection_Date,Release_Date,Molecule_type
195,NC_075965,Mastadenovirus porcusquartum,Mastadenovirus porcusquartum,4,HNU1,31743,complete,China,Sus scrofa,NaN,"Liu,S.-J., Wang,Q., Li,T.-T., Zhang,S.-H., Li,...",2018-07,2023-05-04,dsDNA
197,NC_075980,Teschovirus A,Teschovirus asilesi,17,HuN41,6931,complete,China,Sus scrofa,NaN,"Yang,T., Yu,X.",2017-10,2023-05-04,ssRNA(+)
368,NC_063383,Monkeypox virus,Orthopoxvirus monkeypox,IIb,MPXV-M5312_HM12_Rivers,197209,complete,Nigeria: Rivers State,Homo sapiens,NaN,"Mauldin,M.R., McCollum,A.M., Nakazawa,Y.J., Ma...",2018-08,2022-05-30,dsDNA
447,NC_044856,Norovirus GI,Norovirus norwalkense,GI.Pg-GI.7,NaN,7734,complete,Bangladesh,Homo sapiens,feces,"Nelson,M.I., Mahfuz,M., Chhabra,P., Haque,R., ...",2011-07-06,2019-09-26,ssRNA(+)
687,NC_039028,Squirrel monkey simian foamy virus,Simiispumavirus saisci,SFV4,1224,11684,complete,USA,Saimiri,oronasopharynx,"Pacheco,B., Finzi,A., McGee-Estrada,K., Sodros...",2009-11,2018-08-24,ssRNA-RT

## check basic stats (idk what this means)

In [21]:
sequence.describe()

             Length
count  3.256603e+06
mean   2.946662e+04
std    7.919259e+03
min    1.140000e+02
25%    2.975300e+04
50%    2.984100e+04
75%    2.988400e+04
max    6.599500e+05

## remove `Genotype` column

In [33]:
# remove column
sequence = sequence.drop(columns = ['Genotype'], errors='ignore')

In [32]:
sequence.head()

,Accession,Organism_Name,Species,Isolate,Length,Nuc_Completeness,Geo_Location,Host,Tissue_Specimen_Source,Submitters,Collection_Date,Release_Date,Molecule_type
0,NC_138438,Red panda feces-associated circular DNA virus 12,Alohovirus ailgensis,Rpf011unssDNA01-5,2820,complete,China: Sichuan Province,Ailurus fulgens,feces,"Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...",2020-05,2026-04-07,ssDNA
1,NC_138461,Red panda feces-associated circular DNA virus 11,Protegovirus ailuris,AliP02cress04-2015,2497,complete,China: Sichuan Province,Ailurus fulgens,feces,"Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...",2015,2026-04-07,ssDNA
2,NC_097195,Pacific flying fox faeces associated circular ...,Pekavirus fuais,Tbat_38855,2214,complete,Tonga,Pteropus tonganus,feces,"Male,M.F., Kraberger,S., Stainton,D., Kami,V.,...",2014,2026-04-01,ssDNA
3,NC_099061,Bat circovirus POA/2012/V,Vegetinivirus molmolis,cluster V,1728,complete,Brazil,Chiroptera,feces,"Lima,F.E., Cibulski,S.P., Dos Santos,H.F., Tei...",2012-02-13,2026-04-01,ssDNA
4,NC_116632,Delphin virus 1,Baranavirus uduis,3_2016_1939,1939,complete,Saint Vincent and the Grenadines,Orcinus orca,muscle,"Smith,K., Fielding,R., Schiavone,K., Hall,K., ...",2015-08-26,2026-04-01,ssDNA

## make `Collection_Date` values the same format

In [39]:
# see dtype and existing values
sequence['Collection_Date'].head(20)

0        2020-05
1           2015
2           2014
3     2012-02-13
4     2015-08-26
5        2013-04
6        2013-06
7        2012-12
8           2013
9        2008-08
10    2018-05-22
11       2013-04
12       2013-03
13          2016
14          2016
15          2009
16          2008
17       2013-04
18    2017-03-17
19       2013-04
Name: Collection_Date, dtype: object

In [45]:
# Step 1: Convert to datetime (year-month defaults to 1st, year-only becomes Jan 1st)
sequence['Collection_Date'] = pd.to_datetime(sequence['Collection_Date'], format='mixed', errors='coerce')

In [46]:
# Step 2: Extract year and month for reference
sequence['Year'] = sequence['Collection_Date'].dt.year
sequence['Month'] = sequence['Collection_Date'].dt.month

In [47]:
# Step 3: Identify rows that were originally just a year (month=1 and day=1)
sequence['Original_Day'] = pd.to_datetime(sequence['Collection_Date']).dt.day

In [49]:
# Step 4: For each year, find the mode (most common) month from complete dates
# Then fill in year-only rows with that mode month

for year in sequence['Year'].unique():
    if pd.notna(year):  # Skip NaT years
        year_data = sequence[sequence['Year'] == year]
        
        # Find rows with complete dates (not defaulted to Jan 1st)
        complete_dates = year_data[(year_data['Month'] != 1) | (year_data['Original_Day'] != 1)]
        
        if len(complete_dates) > 0:
            # Get the mode month for that year
            mode_month = complete_dates['Month'].mode()
            
            if len(mode_month) > 0:  # If there is a mode
                mode_month = mode_month[0]
                
                # Update rows that were year-only (Month=1, Day=1)
                year_only_mask = (sequence['Year'] == year) & (sequence['Month'] == 1) & (sequence['Original_Day'] == 1)
                sequence.loc[year_only_mask, 'Collection_Date'] = pd.to_datetime(f'{int(year)}-{int(mode_month):02d}-01')

In [50]:
# Step 5: Update Month column to reflect changes
sequence['Month'] = sequence['Collection_Date'].dt.month

# Step 6: Clean up temporary column
sequence = sequence.drop(columns=['Original_Day'])

# Check results
sequence[['Collection_Date', 'Year', 'Month']].head(20)

   Collection_Date  Year  Month
0       2020-05-01  2020      5
1       2015-03-01  2015      3
2       2014-06-01  2014      6
3       2012-02-13  2012      2
4       2015-08-26  2015      8
5       2013-04-01  2013      4
6       2013-06-01  2013      6
7       2012-12-01  2012     12
8       2013-04-01  2013      4
9       2008-08-01  2008      8
10      2018-05-22  2018      5
11      2013-04-01  2013      4
12      2013-03-01  2013      3
13      2016-07-01  2016      7
14      2016-07-01  2016      7
15      2009-08-01  2009      8
16      2008-09-01  2008      9
17      2013-04-01  2013      4
18      2017-03-17  2017      3
19      2013-04-01  2013      4

In [55]:
# see if it changed the data column
sequence.head()

,Accession,Organism_Name,Species,Isolate,Length,Nuc_Completeness,Geo_Location,Host,Tissue_Specimen_Source,Submitters,Collection_Date,Release_Date,Molecule_type,Year,Month
0,NC_138438,Red panda feces-associated circular DNA virus 12,Alohovirus ailgensis,Rpf011unssDNA01-5,2820,complete,China: Sichuan Province,Ailurus fulgens,feces,"Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...",2020-05-01,2026-04-07,ssDNA,2020,5
1,NC_138461,Red panda feces-associated circular DNA virus 11,Protegovirus ailuris,AliP02cress04-2015,2497,complete,China: Sichuan Province,Ailurus fulgens,feces,"Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...",2015-03-01,2026-04-07,ssDNA,2015,3
2,NC_097195,Pacific flying fox faeces associated circular ...,Pekavirus fuais,Tbat_38855,2214,complete,Tonga,Pteropus tonganus,feces,"Male,M.F., Kraberger,S., Stainton,D., Kami,V.,...",2014-06-01,2026-04-01,ssDNA,2014,6
3,NC_099061,Bat circovirus POA/2012/V,Vegetinivirus molmolis,cluster V,1728,complete,Brazil,Chiroptera,feces,"Lima,F.E., Cibulski,S.P., Dos Santos,H.F., Tei...",2012-02-13,2026-04-01,ssDNA,2012,2
4,NC_116632,Delphin virus 1,Baranavirus uduis,3_2016_1939,1939,complete,Saint Vincent and the Grenadines,Orcinus orca,muscle,"Smith,K., Fielding,R., Schiavone,K., Hall,K., ...",2015-08-26,2026-04-01,ssDNA,2015,8

In [57]:
# missing values in each column
sequence.isnull().sum()

Accession                       0
Organism_Name                   0
Species                         8
Isolate                   1549946
Length                          0
Nuc_Completeness                0
Geo_Location                  336
Host                            0
Tissue_Specimen_Source    2075732
Submitters                1386678
Collection_Date                 0
Release_Date                    0
Molecule_type                   0
Year                            0
Month                           0
dtype: int64

## Making blank values in `Tissue_Specimen_Source` equal to "NaN"

In [60]:
# Replace empty strings and whitespace with actual NaN
sequence['Tissue_Specimen_Source'] = sequence['Tissue_Specimen_Source'].replace(r'^\s*$', np.nan, regex=True)

# Check total NaN values
sequence['Tissue_Specimen_Source'].isnull().sum()

# 2075732 == 2075732

## Making blank values in `Submitters` equal to "NaN"

In [70]:
# replace empty strings and whitespace with NaN
sequence['Submitters'] = sequence['Submitters'].replace(r'^\s*$', np.nan, regex=True)

# Check total NaN values
sequence['Submitters'].isnull().sum()

# 1386678 == 1386678

np.int64(1386678)

## Making blank values in `Isolate` equal to "NaN"

In [67]:
# replace empty strings and whitespace with NaN
sequence['Isolate'] = sequence['Isolate'].replace(r'^\s*$', np.nan, regex=True)

# Check total NaN values
sequence['Isolate'].isnull().sum()

# 1549946 == 1549946

## Making blank values in `Geo_Location` equal to "NaN"

In [74]:
# replace empty strings and whitespace with NaN
sequence['Geo_Location'] = sequence['Geo_Location'].replace(r'^\s*$', np.nan, regex=True)

# Check total NaN values
sequence['Geo_Location'].isnull().sum()

# 336 == 336

np.int64(336)

## Changing countries to regions for "Geo_Location"

In [79]:
# see all countries we have
all_countries = sorted(sequence['Geo_Location'].dropna().unique())
for country in all_countries:
    print(country)

Afghanistan
Afghanistan: Kishim, Badakhshan
Albania
Algeria
Algeria: Berrouaghia-Media
Algeria: Constantine
Algeria: El Bayadh
Algeria: Laghouat-Dakhla
Algeria: M'Sila
Algeria: Medea
Algeria: Ouled Souid, Zemmoura, Relizane
Angola
Angola: Bicuar NP
Angola: Cassongue
Angola: Tundavala
Antarctica
Antarctica: Livingston Island
Antarctica: Ross Sea
Antarctica: Ross ice shelf
Argentina
Argentina: BsAs
Argentina: Buenos Aires
Argentina: Buenos Aires, Adrogue
Argentina: Buenos Aires, Almirante Brown
Argentina: Buenos Aires, Avellaneda
Argentina: Buenos Aires, Banfield
Argentina: Buenos Aires, Beccar
Argentina: Buenos Aires, Bella Vista
Argentina: Buenos Aires, Campana
Argentina: Buenos Aires, Ciudad Evita
Argentina: Buenos Aires, Ciudadela
Argentina: Buenos Aires, Dock Sud
Argentina: Buenos Aires, Don Torcuato
Argentina: Buenos Aires, Escobar
Argentina: Buenos Aires, Esteban Echeverria
Argentina: Buenos Aires, Ezeiza
Argentina: Buenos Aires, Florencio Varela
Argentina: Buenos Aires, Garin
Argentina: Buenos Aires, General Rodriguez
Argentina: Buenos Aires, Gernica
Argentina: Buenos Aires, Gonzalez Catan
Argentina: Buenos Aires, Grand Bourg
Argentina: Buenos Aires, Hurlingham
Argentina: Buenos Aires, Ingeniero Bunge
Argentina: Buenos Aires, Isidro Casanova
Argentina: Buenos Aires, Ituzaingo
Argentina: Buenos Aires, Jose C. Paz
Argentina: Buenos Aires, La Matanza
Argentina: Buenos Aires, La Plata
Argentina: Buenos Aires, Laferrere
Argentina: Buenos Aires, Lanus
Argentina: Buenos Aires, Lomas de Zamora
Argentina: Buenos Aires, Lomas del Mirador
Argentina: Buenos Aires, Los Polvorines
Argentina: Buenos Aires, Lugano
Argentina: Buenos Aires, Malvinas Argentinas
Argentina: Buenos Aires, Manuel Alberti
Argentina: Buenos Aires, Mar del Plata
Argentina: Buenos Aires, Mercedes
Argentina: Buenos Aires, Merlo
Argentina: Buenos Aires, Monte Grande
Argentina: Buenos Aires, Moreno
Argentina: Buenos Aires, Moron
Argentina: Buenos Aires, Munro
Argentina: Buenos Aires, Pablo Nogues
Argentina: Buenos Aires, Paso del Rey
Argentina: Buenos Aires, Pilar
Argentina: Buenos Aires, Rafael Castillo
Argentina: Buenos Aires, San Andres de Giles
Argentina: Buenos Aires, San Fernando
Argentina: Buenos Aires, San Martin
Argentina: Buenos Aires, San Miguel
Argentina: Buenos Aires, San Pedro
Argentina: Buenos Aires, Suipacha
Argentina: Buenos Aires, Temperley
Argentina: Buenos Aires, Tigre
Argentina: Buenos Aires, Tortuguitas
Argentina: Buenos Aires, Valentin Alsina
Argentina: Buenos Aires, Wilde
Argentina: Ciudad Autonoma de Buenos Aires
Argentina: Cordoba
Argentina: Entre Rios
Argentina: Formosa
Argentina: Jujuy
Argentina: Salta
Argentina: Tucuman
Argentina:Buenos Aires
Argentina:Catamarca
Argentina:Chaco
Argentina:Chubut
Argentina:Ciudad Autonoma de Buenos Aires
Argentina:Cordoba
Argentina:Corrientes
Argentina:Entre Rios
Argentina:Formosa
Argentina:Jujuy
Argentina:La Pampa
Argentina:La Rioja
Argentina:Mendoza
Argentina:Misiones
Argentina:Neuquen
Argentina:Rio Negro
Argentina:Salta
Argentina:San Juan
Argentina:San Luis
Argentina:Santa Cruz
Argentina:Santa Fe
Argentina:Santiago del Estero
Argentina:Tierra del Fuego
Argentina:Tucuman
Argentina:not provided
Aruba
Australia
Australia: Bass hill, NSW
Australia: Beatrice Hill, Northern Territory
Australia: Brisbane
Australia: Canberra, ACT
Australia: Central Queensland
Australia: Far North Queensland
Australia: Hallett, South Australia
Australia: Hervey Bay, QLD
Australia: Ipswich, QLD
Australia: Maria Island
Australia: Maria Island, Tasmania
Australia: Melbourne, Victoria
Australia: New South Wales
Australia: North Queensland
Australia: Northern Territory
Australia: Northern Territory, Tiwi Islands
Australia: Queensland
Australia: Queensland, Brisbane
Australia: Queensland, Townsville
Australia: Queensland,ex Bangladesh
Australia: South Australia
Australia: South Brisbane
Australia: South East Queensland
Australia: St George
Australia: Stoney Head, Tasmania
Australia: Sunshine Coast
Australia: Sydney
Australia: Tasmania
Australia: Vic
Australia: Victoria
Australia: WA
Australia: Western Australia
Australia: imported from India
Australia: wukalina/Mt William National Park, Tasmania
Australia:Melbourne
Austria
Austria: Burgenland
Austria: Carinthia
Austria: Lower Austria
Austria: Salzburg
Austria: Styria
Austria: Tyrol
Austria: Upper Austria
Austria: Upper Austria / - /
Austria: Upper Austria / Gmunden / Aigen-Voglhub
Austria: Upper Austria / Gmunden / Bad Goisern
Austria: Upper Austria / Gmunden / Bad Ischl
Austria: Upper Austria / Gmunden / Gmunden
Austria: Upper Austria / Gmunden / Kirchham bei Vorchdorf
Austria: Upper Austria / Gmunden / Laakirchen
Austria: Upper Austria / Gmunden / Oberweis
Austria: Upper Austria / Gmunden / Pinsdorf
Austria: Upper Austria / Gmunden / St. Konrad
Austria: Upper Austria / Gmunden / Vorchdorf
Austria: Upper Austria / Urfahr-Umgebung/ Engerwitzdorf
Austria: Upper Austria / Voecklabruck / Ampflwang im Hausruckwald
Austria: Upper Austria / Voecklabruck / Attnang-Puchheim
Austria: Upper Austria / Voecklabruck / Frankenmarkt
Austria: Upper Austria / Voecklabruck / Lenzing
Austria: Upper Austria / Voecklabruck / Manning
Austria: Upper Austria / Voecklabruck / Mondsee
Austria: Upper Austria / Voecklabruck / Nussdorf am Attersee
Austria: Upper Austria / Voecklabruck / Oberndorf b. Schwanenstadt
Austria: Upper Austria / Voecklabruck / Oberwang
Austria: Upper Austria / Voecklabruck / Ottnang am Hausruck
Austria: Upper Austria / Voecklabruck / Poendorf
Austria: Upper Austria / Voecklabruck / Regau
Austria: Upper Austria / Voecklabruck / Ruestorf
Austria: Upper Austria / Voecklabruck / Schoerfling am Attersee
Austria: Upper Austria / Voecklabruck / Schwanenstadt
Austria: Upper Austria / Voecklabruck / Seewalchen am Attersee
Austria: Upper Austria / Voecklabruck / St. Georgen im Attergau
Austria: Upper Austria / Voecklabruck / St.Lorenz
Austria: Upper Austria / Voecklabruck / Strass im Attergau
Austria: Upper Austria / Voecklabruck / Timelkam
Austria: Upper Austria / Voecklabruck / Voecklabruck
Austria: Upper Austria / Voecklabruck / Voecklamarkt
Austria: Upper Austria / Voecklabruck / Wolfsegg am Hausruck
Austria: Upper Austria / Voecklabruck / Zipf
Austria: Upper Austria, Aigen-Voglhub
Austria: Upper Austria, Altmuenster
Austria: Upper Austria, Attersee
Austria: Upper Austria, Attnang-Puchheim
Austria: Upper Austria, AttnangPuchheim
Austria: Upper Austria, AurachaH
Austria: Upper Austria, Bad Goisern
Austria: Upper Austria, Bad Ischl
Austria: Upper Austria, BadGoisern
Austria: Upper Austria, BadIschl
Austria: Upper Austria, Ebensee
Austria: Upper Austria, Frankenburg am Hausruck
Austria: Upper Austria, Frankenmarkt
Austria: Upper Austria, Gampern
Austria: Upper Austria, Gmunden
Austria: Upper Austria, Gosau
Austria: Upper Austria, Gruenau im Almtal
Austria: Upper Austria, Laakirchen
Austria: Upper Austria, Lenzing
Austria: Upper Austria, Manning
Austria: Upper Austria, Neukirchen
Austria: Upper Austria, NussdorfaA
Austria: Upper Austria, Ohlsdorf
Austria: Upper Austria, Pinsdorf
Austria: Upper Austria, Poendorf
Austria: Upper Austria, Regau
Austria: Upper Austria, Roitham
Austria: Upper Austria, Scharnstein
Austria: Upper Austria, Schwanenstadt
Austria: Upper Austria, Seewalchen
Austria: Upper Austria, St. Georgen im Attergau
Austria: Upper Austria, St.Georgen im Attergau
Austria: Upper Austria, Timelkam
Austria: Upper Austria, Voecklabruck
Austria: Upper Austria, Voecklamarkt
Austria: Upper Austria, Weyregg am Attersee
Austria: Upper Austria, Zell am Moos
Austria: Vienna
Austria:Vienna; Vienna
Azerbaijan
Bahrain
Bahrain: Capital
Bangladesh
Bangladesh: Barishal
Bangladesh: Bhola
Bangladesh: Bogra
Bangladesh: Chattogram
Bangladesh: Chuadanga
Bangladesh: Cox's bazar
Bangladesh: Dhaka
Bangladesh: Dhanbari, Tangail
Bangladesh: Dinajpur
Bangladesh: Faridpur
Bangladesh: Jashore
Bangladesh: Jhalokathi
Bangladesh: Khulna
Bangladesh: Lakshmipur
Bangladesh: Madhupur, Tangail
Bangladesh: Manikgonj
Bangladesh: Mymensingh
Bangladesh: Naogaon
Bangladesh: Narayanganj
Bangladesh: Pabna
Bangladesh: Rajbari
Bangladesh: Rajshahi
Bangladesh: Rangpur
Bangladesh: Raypur, Maniganj
Bangladesh: Sadar, Chittagong
Bangladesh: Shariatpur
Bangladesh: Sylhet
Bangladesh:Dhaka
Bangladesh:Rajshahi
Barbados
Belarus
Belgium
Belgium: BE1745
Belgium: BE2220
Belgium: BE2440
Belgium: BE2460
Belgium: BE2560
Belgium: BE2920
Belgium: BE2990
Belgium: BE3040
Belgium: BE3140
Belgium: BE3472
Belgium: BE3512
Belgium: BE4507
Belgium: BE4690
Belgium: BE4751
Belgium: BE5300
Belgium: BE8480
Belgium: BE8600
Belgium: BE9041
Belgium: BE9070
Belgium: BE9090
Belgium: BE9160
Belgium: BE9240
Belgium: BE9680
Belgium: BE9920
Belgium: BE9971
Belgium: Limburg
Belize
Benin
Benin: Abomey-Calavi
Benin: Benin
Benin: Porto-Novo
Bermuda: WR
Bermuda: WR, Bermuda College COVID-19 Test
Bermuda: WR, COVID-19 Airport Arrival PCR Test
Bermuda: WR, Doctor Entry (PCR) - MDL
Bermuda: WR, KEMH COVID-19 Health Screening
Bermuda: WR, Occupational Health TEST
Bermuda: WR, Omni Medical COVID-19 Test
Bermuda: WR, Perot Post Office Traveller PCR Testing
Bermuda: WR, Perot Quarantine PCR Testing (Entry)
Bermuda: WR, School/Camp PCR Testing
Bermuda: WR, Verification
Bermuda: WR, rhTEST - Dorothy Crane Nursing Home TEST
Bermuda: WR, rhTEST - Herb Garden Rest Home TEST
Bermuda: WR, rhTEST - Lefroy House Care Community TEST
Bermuda: WR, rhTEST - Matilda Smith Williams Seniors Residence TEST
Bermuda: WR, rhTEST - Westmeath Residential & Nursing Care Home TEST
Bermuda: WR, rhTEST- Cynthia,Aos Rest Home TEST
Bhutan
Bhutan: Dagana
Bhutan: Paro
Bhutan: Punakha
Bhutan: Thimphu
Bhutan: Wangdue
Bolivia
Bolivia: Oruro
Bolivia: Santa Cruz
Borneo
Botswana
Brazil
Brazil: Acre
Brazil: Acre state
Brazil: Alagoas
Brazil: Alagoas, Agua Branca
Brazil: Alagoas, Arapiraca
Brazil: Alagoas, Coruripe
Brazil: Alagoas, Delmiro Gouveia
Brazil: Alagoas, Estrela de Alagoas
Brazil: Alagoas, Feira Grande
Brazil: Alagoas, Maceio
Brazil: Alagoas, Maragogi
Brazil: Alagoas, Palmeira dos Indios
Brazil: Alagoas, Piacabucu
Brazil: Alagoas, Sao Jose da Lage
Brazil: Alagoas, Uniao dos Palmares
Brazil: Amapa
Brazil: Amazonas, Manaus
Brazil: Amazonas_Tefe
Brazil: Amorinopolis, GO
Brazil: Ananas
Brazil: Angra dos Reis-RJ
Brazil: Aracatuba city, Sao Paulo
Brazil: Aracatuba, Sao Paulo
Brazil: Araguaina
Brazil: Araras, Petropolis - RJ
Brazil: Bady Bassitt, Sao Paulo
Brazil: Bahia
Brazil: Bahia-BA
Brazil: Belem-PA
Brazil: Belo Horizonte
Brazil: Boa Vista, Roraima State
Brazil: Boa Vista-RR
Brazil: Botucatu, SP
Brazil: Brasilia, DF
Brazil: Caibate
Brazil: Camacari - Bahia
Brazil: Cambe, PR
Brazil: Campinas-SP
Brazil: Carmo - RJ
Brazil: Casimiro de Abreu-RJ
Brazil: Cassilandia, Mato Grosso do Sul
Brazil: Cuiaba, MT
Brazil: Cuiaba, Mato Grosso
Brazil: Cuiaba-MT
Brazil: Cuiaba/MT
Brazil: Cujubin, RO
Brazil: Domingos Martins - ES
Brazil: Domingos Martins-ES
Brazil: Espirito Santo state, Joao Neiva municipality
Brazil: Feira de Santana-BA
Brazil: Fronteira, Sao Paulo
Brazil: Goias
Brazil: Goias State
Brazil: Goias, Cocalzinho de Goias
Brazil: Goias, Faina
Brazil: Goias, Goiania
Brazil: Goias, Uruana
Brazil: Guajara Mirim, RO
Brazil: Guapimirim - RJ
Brazil: Ilha Grande-RJ
Brazil: Itapagipe, Sao Paulo
Brazil: Itapua D'Oeste, RO
Brazil: Ivaipora, Parana
Brazil: Jaru, RO
Brazil: Macae, Atalaia - RJ
Brazil: Macae, Sana - RJ
Brazil: Macae-RJ
Brazil: Macaubal, Sao Paulo
Brazil: Manaus, AM
Brazil: Manaus, Amazonas State
Brazil: Manaus-AM
Brazil: Maranhao
Brazil: Maranhao, Sao Joao do Soter
Brazil: Mato Grosso State
Brazil: Mato Grosso do Sul
Brazil: Mato Grosso do Sul, Campo Grande
Brazil: Mato Grosso do Sul, Dourados
Brazil: Mato Grosso do Sul, Eldorado
Brazil: Miguel Pereira-RJ
Brazil: Minas Gerais
Brazil: Mirassol, Sao Paulo
Brazil: Natal, RN
Brazil: Northern
Brazil: Nossa Senhora do Livramento, MT
Brazil: Nova Alianca, Sao Paulo
Brazil: Nova Crixas - GO
Brazil: Nova Olinda
Brazil: Novo Brasil - GO
Brazil: Novo Horizonte, RO
Brazil: Oiapoque-AP
Brazil: Palestina, Sao Paulo
Brazil: Palmas
Brazil: Para
Brazil: Paraiba
Brazil: Parana
Brazil: Penapolis - Sao Paulo
Brazil: Pernambuco
Brazil: Piaui
Brazil: Piracicaba - Sao Paulo
Brazil: Piraquara, Parana
Brazil: Pocone, MT
Brazil: Porciuncula-RJ
Brazil: Porto Velho, RO
Brazil: Potirendaba, Sao Paulo
Brazil: RJ, Complexo da Mare, BAIXA DO SAPATEIRO
Brazil: RJ, Complexo da Mare, CONJUNTO BENTO RIBEIRO DANTAS
Brazil: RJ, Complexo da Mare, CONJUNTO ESPERANCA
Brazil: RJ, Complexo da Mare, CONJUNTO PINHEIRO
Brazil: RJ, Complexo da Mare, MARCILIO DIAS
Brazil: RJ, Complexo da Mare, MORRO DO TIMBAU
Brazil: RJ, Complexo da Mare, NOVA HOLANDA
Brazil: RJ, Complexo da Mare, NOVO PINHEIRO
Brazil: RJ, Complexo da Mare, NOVO PINHEIRO (SALSA E MERENGUE)
Brazil: RJ, Complexo da Mare, PARQUE MARE
Brazil: RJ, Complexo da Mare, PARQUE RUBENS VAZ
Brazil: RJ, Complexo da Mare, PARQUE UNIAO
Brazil: RJ, Complexo da Mare, PINHEIROS
Brazil: RJ, Complexo da Mare, RAMOS
Brazil: RJ, Complexo da Mare, ROQUETE PINTO
Brazil: RJ, Complexo da Mare, RUBENS VAZ
Brazil: RJ, Complexo da Mare, VILA DO JOAO
Brazil: RJ, Complexo da Mare, VILA DO PINHEIRO
Brazil: RJ, Complexo da Mare, VILA DO PINHEIRO (PARQUE ECOLOGICO)
Brazil: Recife-PE
Brazil: Ribeirao Preto (Sao Paulo)
Brazil: Ribeirao Preto, Sao Paulo
Brazil: Rio Grande do Norte
Brazil: Rio Grande do Norte, Natal
Brazil: Rio Grande do Norte_Espirito Santo
Brazil: Rio de Janeiro
Brazil: Rio de Janeiro, Favela da Mare
Brazil: Rio de Janeiro, Miracema
Brazil: Rio de Janeiro, Rio de Janeiro '', ''Complexo da Mare
Brazil: Rio de Janeiro, Rio de Janeiro, Complexo da Mare.
Brazil: Rondonia
Brazil: Roraima
Brazil: SP, Sao Jose do Rio Preto
Brazil: Salvador
Brazil: Salvador - Bahia
Brazil: Santa Fe, Carmo - RJ
Brazil: Santarem-PA
Brazil: Santos, SP
Brazil: Santos, Sao Paulo
Brazil: Sao Fidelis-RJ
Brazil: Sao Francisco - Minas Gerais
Brazil: Sao Jose do Rio Preto, Sao Paulo
Brazil: Sao Paulo
Brazil: Sao Paulo - SP
Brazil: Sao Paulo, Aguas da Prata
Brazil: Sao Paulo, Aruja
Brazil: Sao Paulo, Assis
Brazil: Sao Paulo, Atibaia
Brazil: Sao Paulo, Bertioga
Brazil: Sao Paulo, Cacapava
Brazil: Sao Paulo, Campo Limpo Paulista
Brazil: Sao Paulo, Cotia
Brazil: Sao Paulo, Cubatao
Brazil: Sao Paulo, Cunha
Brazil: Sao Paulo, Guaruja
Brazil: Sao Paulo, Guarulhos
Brazil: Sao Paulo, Ibiuna
Brazil: Sao Paulo, Iporanga
Brazil: Sao Paulo, Itanhaem
Brazil: Sao Paulo, Itaquaquecetuba
Brazil: Sao Paulo, Itariri
Brazil: Sao Paulo, Mairipora
Brazil: Sao Paulo, Osasco
Brazil: Sao Paulo, Pedreira
Brazil: Sao Paulo, Peruibe
Brazil: Sao Paulo, Piedade
Brazil: Sao Paulo, Ribeirao Preto
Brazil: Sao Paulo, SP
Brazil: Sao Paulo, Santos
Brazil: Sao Paulo, Sao Joao da Boa Vista
Brazil: Sao Paulo, Sao Jose do Rio Preto
Brazil: Sao Paulo, Sao Jose dos Campos
Brazil: Sao Paulo, Sao Lourenco da Serra
Brazil: Sao Paulo, Sao Paulo
Brazil: Sao Paulo, Sao Vicente
Brazil: Sao Paulo, Taubate
Brazil: Sao Sebastiao do Passe - Bahia
Brazil: Sao Vicente
Brazil: Senador Canedo, Goias
Brazil: Sinop, MT
Brazil: South America, Rio de Janeiro, Macae
Brazil: Southeast
Brazil: St Fe do Araguaia
Brazil: Teodoro Sampaio, Sao Paulo
Brazil: Teresopolis-RJ
Brazil: Thelbroma, RO
Brazil: Uchoa, Sao Paulo
Brazil: Vale do Ribeira, Sao Paulo
Brazil: Vale do Ribeirao, Sao Paulo
Brazil: Varzea Grande, MT
Brazil: Varzea Grande/MT
Brazil: Viseu
Brazil: Viseu city, Para state
Brazil:Para, Afua
Brazil:Para, Anajas
Brazil:Para, Bagre
Brazil:Para, Melgaco
Brazil:Para, Soure
Brazil:South America / Brazil / Amazonas / Manaus
Brazil:South America / Brazil / Bahia / Salvador
Brazil:South America / Brazil / Distrito Federal / Brasilia
Brazil:South America / Brazil / Goias / Aguas Lindas de Goias
Brazil:South America / Brazil / Goias / Anapolis
Brazil:South America / Brazil / Goias / Cristalina
Brazil:South America / Brazil / Goias / Formosa
Brazil:South America / Brazil / Goias / Luziania
Brazil:South America / Brazil / Para / Belem
Brazil:South America / Brazil / Roraima / Boa Vista
Brazil:South America / Brazil / Sao Paulo / Campinas
Brazil:South America / Brazil / Sao Paulo / Ribeirao Preto
Brazil:South America / Brazil / Sao Paulo / Sao Jose dos Campos
British Virgin Islands
Brunei
Bulgaria
Bulgaria: Fakia, Sredets
Bulgaria: Goliamo Bukovo, Sredets
Bulgaria: Granichar, Sredets
Bulgaria: Jambul
Bulgaria: Kirovo, Sredets
Bulgaria: Kosti, Maketvetci, Tsarevo
Bulgaria: Kosti, Tsarevo
Bulgaria: Momina Tsarkva, Sredets
Bulgaria: Rezovo, Tsarevo
Bulgaria: Yambol region
Burkina Faso
Burundi
Cambodia
Cambodia: BMC
Cambodia: BTB
Cambodia: Banteay Mean Chey
Cambodia: Banteay Meanchey
Cambodia: Battam Bong
Cambodia: Battambang
Cambodia: KAN
Cambodia: KCH
Cambodia: KOP
Cambodia: KSP
Cambodia: Kampong Cham
Cambodia: Kampong Cham Hospital
Cambodia: Kampong Speu
Cambodia: Kampong Thom
Cambodia: Kampot
Cambodia: Kandal
Cambodia: Kandaldal
Cambodia: Kratie
Cambodia: PHP
Cambodia: PRV
Cambodia: Pailin
Cambodia: Phnom Penh
Cambodia: Phnom penh
Cambodia: Prey Veng
Cambodia: SRP
Cambodia: Siem Reab
Cambodia: Siem Reap
Cambodia: Svay Reang
Cambodia: TAK
Cambodia: Takeo
Cambodia:Battambang Province
Cambodia:Kampong Cham Province
Cambodia:Kampong Speu Province
Cambodia:Kampong Thom Province
Cambodia:Kandal Province
Cambodia:Kracheh Province
Cambodia:Kracheh Provinde
Cambodia:Otdar Meanchey Province
Cambodia:Phnom Penh
Cambodia:Preah Sihanouk Province
Cambodia:Preah Vihear Province
Cambodia:Pursat Province
Cambodia:Ratanak Kiri Province
Cambodia:Siem Reap Province
Cambodia:Stung Treng Province
Cambodia:Svay Rieng Province
Cambodia:Takeo Province
Cambodia:Tboung Khmum Province
Cameroon
Cameroon: Centre Region
Cameroon: Dembo, North Region
Cameroon: Limbe Wildlife Centre
Cameroon: Mfou NP sanctuary
Cameroon: Mukunda Limbe
Cameroon: Yaounde
Cameroon:Centre
Cameroon:North-West
Cameroon:North-west
Cameroon:South-west
Canada
Canada: AB, Canmore
Canada: Alberta
Canada: Alberta, Calgary
Canada: Ange-Gardien, Rouville, QC
Canada: Bayside, Charlotte, NB
Canada: Bedford, Brome-Missisquoi, QC
Canada: Bocabec, Charlotte, NB
Canada: British Columbia
Canada: British Columbia, Graham Island
Canada: British Columbia, Vancouver Island
Canada: Burnt Hill, Charlotte, NB
Canada: Chamcook, Charlotte, NB
Canada: Clarenceville, Le Haut-Richelieu, QC
Canada: Comox, BC
Canada: Cooks Lane, Charlotte, NB
Canada: Cowansville, Brome-Missisquoi, QC
Canada: Dunham, Brome-Missisquoi, QC
Canada: Farnham, Brome-Missisquoi, QC
Canada: Farnham, Le Haut-Richelieu, QC
Canada: Frelighsburg, Brome-Missisquoi, QC
Canada: Hamilton, Hamilton, ON
Canada: Henryville, Le Haut-Richelieu, QC
Canada: Labrador
Canada: Lethbridge, AB
Canada: MB
Canada: Manitoba
Canada: McAdam, York, NB
Canada: Mont-Saint-Gregoire, Brome-Missisquoi, QC
Canada: NS
Canada: Newfoundland
Canada: Newfoundland and Labrador
Canada: Northern Territories
Canada: Northwest Territories
Canada: Noyan, Brome-Missisquoi, QC
Canada: Noyan, Le Haut-Richelieu, QC
Canada: Nunavut
Canada: ON
Canada: ONTARIO, ON K8P 4L2
Canada: Oak Bay, Charlotte, NB
Canada: Ontario
Canada: Ottawa
Canada: Parksville, BC
Canada: Pennfield, Charlotte, NB
Canada: Province of Quebec, Quebec city
Canada: QC, Saint-Jean-sur-Richelieu
Canada: QC, Verdun
Canada: Quebec
Canada: Regina, Saskatchewan
Canada: Saint-Alexandre, Le Haut-Richelieu, QC
Canada: Saint-Armand, Brome-Missisquoi, QC
Canada: Saint-C_saire, Rouville, QC
Canada: Saint-Georges-de-Clarenceville, Le Haut-Richelieu, QC
Canada: Saint-Jean-sur-Richelieu, Brome-Missisquoi, QC
Canada: Saint-Jean-sur-Richelieu, Le Haut-Richelieu, QC
Canada: Saint-Pierre-de-Veronne-a-Pike-River, Brome-Missisquoi, QC
Canada: Saint-S_bastien, Brome-Missisquoi, QC
Canada: Sainte-Anne-de-Sabrevois, Le Haut-Richelieu, QC
Canada: Sainte-Sabine, Brome-Missisquoi, QC
Canada: Saskatchewan
Canada: Saskatoon, SK
Canada: Silverwood heights, Saskatoon, Saskatchewan
Canada: St Regis, Akwesasne Reservation, QC
Canada: St. Andrews, Charlotte, NB
Canada: St. Stephen, Charlotte, NB
Canada: Stanbridge East, Brome-Missisquoi, QC

In [84]:
import pycountry_convert as pc
import numpy as np

def get_continent(location):
    if pd.isna(location):
        return np.nan
    
    # Extract just the country name (before the colon)
    country = location.split(':')[0].strip()
    
    try:
        # Handle special cases
        if country == 'USA':
            return 'North America'
        elif country == 'UK' or country == 'United Kingdom':
            return 'Europe'
        elif country in ['Viet Nam', 'Vietnam']:
            return 'Asia'
        elif country == 'Antarctica':
            return 'Antarctica'
        elif country == 'Reunion':
            return 'Africa'
        elif country == "Cote d'Ivoire":
            return 'Africa'
        elif country == 'West Bank':
            return 'Asia'
        elif country == 'Kosovo':
            return 'Europe'
        elif country == 'Timor-Leste':
            return 'Asia'
        elif country == 'Borneo':
            return 'Asia'
        elif country == 'Korea':
            return 'Asia'
        elif country == 'Saint Barthelemy':
            return 'North America'
        elif country == 'Gaza Strip':
            return 'Asia'
        
        # Use the library for standard countries
        country_code = pc.country_name_to_country_alpha2(country)
        continent_code = pc.country_alpha2_to_continent_code(country_code)
        continent = pc.convert_continent_code_to_continent_name(continent_code)
        return continent
    except:
        return np.nan

# Apply the function
sequence['Continent'] = sequence['Geo_Location'].apply(get_continent)

# Check what didn't convert
unmapped = sequence[sequence['Continent'].isnull()]['Geo_Location'].value_counts()
print(f"Unmapped locations: {len(unmapped)}")

Unmapped locations: 0

In [85]:
unmapped = sequence[sequence['Continent'].isnull()]['Geo_Location'].value_counts()
print(unmapped)

Series([], Name: count, dtype: int64)

In [86]:
sequence.head()

,Accession,Organism_Name,Species,Isolate,Length,Nuc_Completeness,Geo_Location,Host,Tissue_Specimen_Source,Submitters,Collection_Date,Release_Date,Molecule_type,Year,Month,Continent
0,NC_138438,Red panda feces-associated circular DNA virus 12,Alohovirus ailgensis,Rpf011unssDNA01-5,2820,complete,China: Sichuan Province,Ailurus fulgens,feces,"Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...",2020-05-01,2026-04-07,ssDNA,2020,5,Asia
1,NC_138461,Red panda feces-associated circular DNA virus 11,Protegovirus ailuris,AliP02cress04-2015,2497,complete,China: Sichuan Province,Ailurus fulgens,feces,"Zhao,M., Yue,C., Yang,Z., Li,Y., Zhang,D., Zha...",2015-03-01,2026-04-07,ssDNA,2015,3,Asia
2,NC_097195,Pacific flying fox faeces associated circular ...,Pekavirus fuais,Tbat_38855,2214,complete,Tonga,Pteropus tonganus,feces,"Male,M.F., Kraberger,S., Stainton,D., Kami,V.,...",2014-06-01,2026-04-01,ssDNA,2014,6,Oceania
3,NC_099061,Bat circovirus POA/2012/V,Vegetinivirus molmolis,cluster V,1728,complete,Brazil,Chiroptera,feces,"Lima,F.E., Cibulski,S.P., Dos Santos,H.F., Tei...",2012-02-13,2026-04-01,ssDNA,2012,2,South America
4,NC_116632,Delphin virus 1,Baranavirus uduis,3_2016_1939,1939,complete,Saint Vincent and the Grenadines,Orcinus orca,muscle,"Smith,K., Fielding,R., Schiavone,K., Hall,K., ...",2015-08-26,2026-04-01,ssDNA,2015,8,North America

## SAVE THE DATAAAA

In [88]:
sequence.to_csv('/Users/delaneyvanderpool/Desktop/research_2026/pathology_genomics/spillover_model/data/processed/sequences_cleaned.csv', index=False)